### ISSUE TITLE
Auto-filter in Search-Box of Kouncil UI 1.5 

### ISSUE THREAD

**Issue by iemsed** [Consdata/kouncil#300] opened 2023-03-15 10:20 UTC
**Description**
When using Kouncil UI 1.5, the filter field is not responding as it used to do. When something is typed, the filter does not get triggered properly.

**Expected Result**
The filter should be triggered (so the results must be shown) while typing in the filter field like it was with Kouncil 1.3.

**Workaround**
When typing a search string in the search-box and then pressing space followed by backspace, the search result is updated.

**Kouncil version**
Docker: consdata/kouncil:1.5

**Browsers**
Chrome Version 111.0.5563.65 (Official Build) (64-bit); Firefox 110.0.1 (64-Bit)

**Question**
Is there anything you can do about it? Or has this behavior been removed on purpose?

**Comment by pbelke** [comment] 2023-03-18 15:15
@iemsed we can definitely do something about it. 
We found what is the cause of the behavior you described and we will fix this in the next released version

**Comment by pbelke** [comment] 2023-11-26 15:15
Fixed with released version 1.6

**Closed by pbelke** 2023-11-26 15:15 UTC
